markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Doug Ayers
url: https://douglascayers.github.io
description: My journey with Salesforce and technology
twitter: DouglasCAyers
