name: Doug Ayers
url: https://douglascayers.github.io
description: My journey with Salesforce and technology
twitter: douglascayers

permalink: /posts/:title

gems:
  - jekyll-sitemap

stylesheets:
  - <link rel="alternate" type="application/rss+xml" href="/atom.xml"/>
  - <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" type="text/css"/>
  - <link href="{{ site.github.url }}/css/base.css" rel="stylesheet" type="text/css" media="screen, projection"/>
  - <link href="{{ site.github.url }}/css/pygments.css" rel="stylesheet" type="text/css"/>
  - <link href="{{ site.github.url }}/css/mobile.css" rel="stylesheet" type="text/css" media="only screen and (max-device-width: 480px)"/>
  - <link href="{{ site.github.url }}/css/mobile.css" rel="stylesheet" type="text/css" media="only screen and (device-width: 768px)"/>
  - <link href="https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz" rel="stylesheet" type="text/css">
  - <link href="{{ site.github.url }}/apple-touch-icon.png" rel="apple-touch-icon"/>
